platforms:
- name: T2
  repo: https://github.com/tuya/TuyaOpen-T2
  branch: master
  commit: 8978e4b9f9d3b46700fb49801c715cc84f34571d

- name: T3
  repo: https://github.com/tuya/TuyaOpen-T3
  branch: master
  commit: 113aaef3d4838fd1665d88756fe906f56e3eb402

- name: Ubuntu
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  branch: platform_ubuntu
  commit: 2d009224c5c6cebbfe09a9eebefa117dda97ffca

- name: T5AI
  repo: https://github.com/tuya/TuyaOpen-T5AI
  branch: master
  commit: 44c25122bddb53bbcd4f09bafb981e5694415f17

- name: ESP32
  repo: https://github.com/tuya/TuyaOpen-esp32
  branch: master
  commit: 2efe28ec6182e1e335d8844fe4aa7e22946db701

- name: LN882H
  repo: https://github.com/tuya/TuyaOpen-ln882h
  branch: master
  commit: 74e0f72f98f7ba33d9bf82e0ce795ffe273b4e9f

- name: BK7231X
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  branch: master
  commit: 00c95e3dd3fdf823c983ba3b9ea3d02120924eb4
